# Generated by Django 2.1 on 2018-08-19 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20180811_1856'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postmodel',
            options={'ordering': ['-created_at', 'update_at']},
        ),
    ]
