# Generated by Django 2.1 on 2018-08-16 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20180816_2206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlemodel',
            options={'ordering': ['-timestamp', '-updated']},
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='description',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
