# Generated by Django 2.1 on 2018-08-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20180816_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='read_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
