# Generated by Django 2.1 on 2018-08-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_articlemodel_read_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='read_time',
            field=models.IntegerField(default=0),
        ),
    ]
