# Generated by Django 2.0.4 on 2018-08-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextramodel',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/profile_pics'),
        ),
    ]
