# Generated by Django 2.0.4 on 2018-08-03 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20180803_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextramodel',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
