# Generated by Django 2.1 on 2018-09-09 12:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_auto_20180909_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextramodel',
            name='follower',
            field=models.ManyToManyField(blank=True, null=True, related_name='is_following', to=settings.AUTH_USER_MODEL),
        ),
    ]
